### ISSUE TITLE
Ideas for new functionality

### ISSUE THREAD

**Issue by bc38** [simondreutter/cruisetools#1]
Thanks for your plugin! The tools are very useful for those making their own bathymetric charts for fishing and safe navigation.
I have wishes for new tools that are sorely lacking when working with hydrographic survey materials.
1. Creation of bathymetry of their points in XYZ format. Ability to add multiple files. Option to create bathymetry along polygon boundaries.
2. Entering the correction of the sound velocity profile at the depth points. Possibility of direct input of values ​​for recalculation of depths or use of a file of results of measurements of the sound velocity profile in water.
3. The function of sampling and thinning out points of depth marks. The function of sampling for extracting depth marks from a common base for a specified range from and to with saving in a separate file. The function of thinning depth marks at a given distance with saving to a separate file.

**Comment by simondreutter** [comment]
Hiya,

Thanks for your input, but I'm thinking, you are mistaking our plugin for a full multibeam data processing software. Implementing SVC algorithms would require an entire handling of raw bathymetry data formats, etc. While I'd love to do my multibeam processing in QGIS, I'm afraid, this is far out of the scope of this plugin.
Yet, if you need an open source multibeam processing utility, I'm gladly pointing you towards [MB-System](https://www.mbari.org/products/research-software/mb-system/). MB-System can also deal with XYZ data, import multiple files and create bathymetry grids from those input files.

**Comment by bc38** [comment]
> Hiya,
> 
> Thanks for your input, but I'm think, you are mistaking our plugin for a full multibeam data processing software. Implementing SVC algorithms would require and entire handling of raw bathymetry data formats, etc. While I'd love to do my multibeam processing in QGIS, I'm afraid, this is far out of the scope of this plugin.
> Yet, if you need an open source multibeam processing utility, I'm gladly pointing you towards [MB-System](https://www.mbari.org/products/research-software/mb-system/). MB-System can also deal with XYZ data, import multiple files and create bathymetry grids from those input files.

Multi-beam echo sounder is of course very cool! But we are regular single-beam anglers who create a depth map of their reservoir for a chartplotter.
It is possible to make a model of the bottom relief and isobaths in the same QGIS, but making beautiful depth marks (an uncluttered number of points) is problematic. The thinning function is available in [specialized hydrographic software](https://youtu.be/jgtC85d2dl8) that is not available to me. I tried in QGIS the SAGA Points Thinning analysis tool seems to be what I need, but he comes up with his new points and does not filter the existing ones. Such a correct thinning task is in demand among qgis users and not only in filtering depth marks. Building a complete MB or SB post-processing tool in qgis is not a lifting task. Those who have MB are likely to have special software for processing. MBS on your link under Windows does not work unfortunately.

**Comment by simondreutter** [comment]
Ah, I understand. Sorry to say, but this is not exactly, what cruisetools was written for.

It sounds like, you need a gridded representation of your unstructured measurement points. You could achieve this with creating a gridded point feature and running a nearest neighbor join on your SBES data points.

Or see if your SBES output format is supported by MB-System. There is also a version running on Windows, just slightly outdated and without the GUI tools.

http://joa-quim.pt/mirone/downloads/mb-system.html
